spring:
  application:
    name: socle-effyis
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none  # Prevent Hibernate from Automatic Changes to the DDL Schema
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    initialization-mode: never  # Prevent JPA from trying to Initialize
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: email
    password: password
    sign: Effyis
    location: Casablanca
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

ldap:
  urls: ldap://ldap.forumsys.com:389/
  base:
    dn: dc=example,dc=com 
  username: cn=read-only-admin,dc=example,dc=com
  password: password 
  user:
    dn:
      pattern: uid={0}
            
security:
  public:
    endpoint: /effyis/api/api-docs/**,/effyis/api/swagger-ui/**,/effyis/api/accounts/login
  jwt:
    secret: secret
    expiration:
      time: 2592000000
  cors:
    allowed:
      origins: http://localhost:4200,http://127.0.0.1:4200

springdoc:
  swagger-ui:
    path: /effyis/api/swagger-ui
  api-docs:
    path: /effyis/api/api-docs

server:
  port : 9000

default:
  role: DEFAULT
  
config:
  datasources:
    -
      url: jdbc:postgresql://localhost:5432/socle_db
      username: postgres
      password: postgres
      client: client1
    -
      url: jdbc:postgresql://localhost:5432/socle_db
      username: postgres
      password: postgres
      client: client2
      

datasource:
  max:
    pool:
      size: 20
  min:
    idle: 10
  idle:
    timeout: 120000